server:
  port: 16321
spring:
  application:
    name: gbt32960.3_tcp_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.71:3306/gbt32960?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: 1qaz0OKM
  data:
    redis:
      host: 192.168.31.71
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 7
      # 密码
      password: 1qaz0OKM
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

netty:
  server:
    host: 0.0.0.0
    use-epoll: false
    heart-seconds: 300
    vehicle-port: 20000
    platform-port: 20001
    platform-cache-size: 52428800
    vehicle-cache-size: 5120

logging:
  config: classpath:logback.xml

node:
  name: node1
  host: 127.0.0.1:16321
